# Generated by Django 5.0.2 on 2024-03-03 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0003_car_langitude_car_latitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('desired_date', models.DateTimeField(verbose_name='До какого времени аренда')),
                ('start_rent_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала аренды')),
                ('status', models.CharField(choices=[('UC', 'На рассмотрении'), ('AD', 'Одобрен'), ('RD', 'Отклонен')], default='UC', max_length=2, verbose_name='Статус')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
                ('сar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Арендованный автомобиль')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
    ]
