# Generated by Django 5.0.2 on 2024-02-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_caroptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='langitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
