# Generated by Django 5.0.2 on 2024-03-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_car_brandphoto_brand_alter_brandphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='brandphoto',
            options={'verbose_name': 'Фотография бренда',
                     'verbose_name_plural': 'Фотографии бренда'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель автомобиля',
                     'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='carmodelphoto',
            options={'verbose_name': 'Фотография модели машины',
                     'verbose_name_plural': 'Фотографии моделей машины'},
        ),
        migrations.AlterField(
            model_name='brandphoto',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='brand_photo', to='cars.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='brandphoto',
            name='photo',
            field=models.ImageField(upload_to='brands', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type_of_fuel',
            field=models.CharField(choices=[('92', 'АИ-92'), ('95', 'АИ-95'), ('10', 'АИ-100'), ('GS', 'Газ'), ('DT',
                                   'Дизельное топливо'), ('EL', 'Электричество')], max_length=10, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='carmodelphoto',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='carmodel_photo', to='cars.carmodel', verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='carmodelphoto',
            name='photo',
            field=models.ImageField(
                upload_to='car_models', verbose_name='Фото'),
        ),
    ]
