# Generated by Django 4.0 on 2024-03-05 10:46

from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_car_brandphoto_brand_alter_brandphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandphoto',
            name='photo',
            field=models.FileField(storage=django_minio_backend.models.MinioBackend(bucket_name='car_rent_bucket', replace_existing=True), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
