# Generated by Django 5.0.2 on 2024-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь',
                     'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('NV', 'Не верифицирован'), ('VE', 'Верифицирован'), (
                'SU', 'Подозреваемый'), ('BA', 'Заблокирован')], default='NV', max_length=2, verbose_name='Статус'),
        ),
    ]
